services:
  mongo:
    image: mongo:5
    ports: ["27017:27017"]
    volumes: [mongo_data:/data/db]

  redis:
    image: redis:6
    ports: ["6379:6379"]

  flask:
    build:
      context: .
      dockerfile: flask_app/Dockerfile
    ports: ["5050:5000"]
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    depends_on:
      - mongo
      - redis
    volumes:
      - ./flask_app:/app
      - ./celery_worker:/app/celery_worker   # if your Flask imports the worker package

  celery:
    build:
      context: .
      dockerfile: celery_worker/Dockerfile
    command: celery -A celery_worker.tasks worker --loglevel=info
    environment:
      - PYTHONPATH=/app
      - MONGO_URL=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./celery_worker:/app/celery_worker

  celery-beat:
    build:
      context: .
      dockerfile: celery_worker/Dockerfile
    command: celery -A celery_worker.tasks beat --loglevel=info
    environment:
      - PYTHONPATH=/app
      - MONGO_URL=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379/0
      - MODEL_NAME=eg_ci
      - STRATEGY_NAME=cointegration
    depends_on:
      - redis
    volumes:
      - ./celery_worker:/app/celery_worker

volumes:
  mongo_data:
