version: "3.9"

services:
  flask:
    build:
      context: .
      dockerfile: flask_app/Dockerfile
    ports:
      - "5050:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mongo
      - redis

  celery:
    build:
      context: .
      dockerfile: celery_worker/Dockerfile
    command: celery -A celery_worker.tasks worker --loglevel=info
    depends_on:
      - redis
    environment:
      - PYTHONPATH=/app
    

  celery-beat:
    build:
      context: .
      dockerfile: celery_worker/Dockerfile
    command: celery -A celery_worker.tasks beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - PYTHONPATH=/app


  mongo:
    image: mongo:5
    ports:
      - "27017:27017"

  redis:
    image: redis:6
    ports:
      - "6379:6379"